deepfashion2:
  max_images: 1  # 设置需要处理的最大图片数量
  train_image_dir: "./garment_editing/data/raw/DeepFashion2 Dataset/train/image"
  train_annos_dir: "./garment_editing/data/raw/DeepFashion2 Dataset/train/annos"
  train_output_dir: "./garment_editing/data/processed/deepfashion2/train"

  validation_image_dir: "./garment_editing/data/raw/DeepFashion2 Dataset/validation/image"
  validation_annos_dir: "./garment_editing/data/raw/DeepFashion2 Dataset/validation/annos"
  validation_output_dir: "./garment_editing/data/processed/deepfashion2/validation"

  test_image_dir: "./garment_editing/data/raw/DeepFashion2 Dataset/test/image"

  # 兼容性保持：基础输出目录
  output_dir: "./garment_editing/data/processed/deepfashion2"

human_parsing:
  root: "./garment_editing/data/raw/Human_Parsing_Dataset"
  output_dir: "./garment_editing/data/processed/human_parsing"

  train_image_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Training/Images"
  train_annos_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Training"
  train_output_dir: "./garment_editing/data/processed/human_parsing/train"

  validation_image_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Validation/Images"
  validation_annos_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Validation"
  validation_output_dir: "./garment_editing/data/processed/human_parsing/validation"

  test_image_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Testing/Images"
  test_annos_dir: "./garment_editing/data/raw/Human_Parsing_Dataset/CIHP/instance-level_human_parsing/Testing"
  test_output_dir: "./garment_editing/data/processed/human_parsing/test"

resize: true
image_size: [256, 256]

